[colors.normal]
black = "0x45475a"
blue = "0x89b4fa"
cyan = "0x94e2d5"
green = "0xa6e3a1"
magenta = "0xf5c2e7"
red = "0xf38ba8"
white = "0xcdd6f4"
yellow = "0xf9e2af"

[colors.primary]
background = "0x1e1e2e"
foreground = "0xcdd6f4"

[font]
size = 12  # Adjust font size


[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },  # Ctrl+Shift+V to paste
  { key = "C", mods = "Control|Shift", action = "Copy" }    # Ctrl+Shift+C to copy
]


[scrolling]
history = 10000
multiplier = 10

[window]
opacity = 0.85
